/** Curated icon choices for the "change this panel's icon" picker. Stored
 *  state only ever holds the string key on the left — never a component
 *  reference — so a saved workspace stays plain JSON. */
import {
  Activity,
  BookOpen,
  Briefcase,
  Calendar,
  Camera,
  CheckCircle,
  Clock,
  Cloud,
  Coffee,
  Compass,
  Dumbbell,
  Feather,
  Flag,
  Flame,
  Gift,
  Globe,
  Heart,
  HeartHandshake,
  Home,
  Image,
  Lightbulb,
  List,
  Map,
  Medal,
  Mountain,
  Music,
  PenLine,
  Quote,
  Rocket,
  Smile,
  Sparkles,
  Star,
  Sun,
  Target,
  Trophy,
  Video,
  Wallet,
  type LucideIcon,
} from 'lucide-react';

export const PANEL_ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  bookOpen: BookOpen,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  checkCircle: CheckCircle,
  clock: Clock,
  cloud: Cloud,
  coffee: Coffee,
  compass: Compass,
  dumbbell: Dumbbell,
  feather: Feather,
  flag: Flag,
  flame: Flame,
  gift: Gift,
  globe: Globe,
  heart: Heart,
  heartHandshake: HeartHandshake,
  home: Home,
  image: Image,
  lightbulb: Lightbulb,
  list: List,
  map: Map,
  medal: Medal,
  mountain: Mountain,
  music: Music,
  penLine: PenLine,
  quote: Quote,
  rocket: Rocket,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  target: Target,
  trophy: Trophy,
  video: Video,
  wallet: Wallet,
};

export const PANEL_ICON_KEYS = Object.keys(PANEL_ICONS);
