/** Placeholder content for the "fill with sample" button. Deliberately generic,
 *  and written per language rather than machine-translated at runtime.
 *  Vision-board images are generated by the main process, not listed here. */
import type { Language } from './i18n/strings';
import { newId } from './lib/id';
import { emptyLists, type Item, type Lists, type VideoItem } from './types';

const toItems = (texts: string[]): Item[] => texts.map((text) => ({ id: newId(), text }));

type ListKey = 'goals' | 'values' | 'strengths' | 'gratitude' | 'affirmations' | 'quotes';

const SAMPLES: Record<Language, Record<ListKey, string[]>> = {
  en: {
    goals: ['Start a morning routine', 'Read 12 books this year', 'Learn a new skill', 'Exercise three times a week'],
    values: ['Growth', 'Health', 'Family', 'Learning', 'Creativity'],
    strengths: ['Creativity', 'Persistence', 'Problem solving', 'Adaptability'],
    gratitude: ['Supportive family and friends', 'Good health', 'Opportunities to learn and grow', 'A peaceful place to work'],
    affirmations: [
      'I am constantly growing and improving',
      'I create positive impact in everything I do',
      'Every challenge is an opportunity to learn',
    ],
    quotes: [
      '"The only way to do great work is to love what you do" — Steve Jobs',
      '"Success is not final, failure is not fatal" — Winston Churchill',
      '"Start where you are. Use what you have" — Arthur Ashe',
    ],
  },
  he: {
    goals: ['להתחיל שגרת בוקר', 'לקרוא 12 ספרים השנה', 'ללמוד מיומנות חדשה', 'להתאמן שלוש פעמים בשבוע'],
    values: ['צמיחה', 'בריאות', 'משפחה', 'למידה', 'יצירתיות'],
    strengths: ['יצירתיות', 'התמדה', 'פתרון בעיות', 'גמישות'],
    gratitude: ['משפחה וחברים תומכים', 'בריאות טובה', 'הזדמנויות ללמוד ולצמוח', 'מקום שקט לעבוד בו'],
    affirmations: ['אני צומח ומשתפר כל הזמן', 'אני יוצר השפעה חיובית בכל מה שאני עושה', 'כל אתגר הוא הזדמנות ללמוד'],
    quotes: [
      '"הדרך היחידה לעשות עבודה נהדרת היא לאהוב את מה שאתה עושה" — סטיב ג׳ובס',
      '"הצלחה אינה סופית, כישלון אינו קטלני" — וינסטון צ׳רצ׳יל',
      '"התחל מהמקום שבו אתה נמצא. השתמש במה שיש לך" — ארתור אש',
    ],
  },
};

const SAMPLE_VIDEOS: Record<Language, Array<{ title: string; url: string }>> = {
  en: [
    { title: 'Steve Jobs — Stanford commencement', url: 'https://www.youtube.com/watch?v=UF8uR6Z6KLc' },
    { title: 'Simon Sinek — Start with why', url: 'https://www.youtube.com/watch?v=qp0HIF3SfI4' },
  ],
  he: [
    { title: 'סטיב ג׳ובס — נאום הסיום בסטנפורד', url: 'https://www.youtube.com/watch?v=UF8uR6Z6KLc' },
    { title: 'סיימון סינק — התחל מ״למה״', url: 'https://www.youtube.com/watch?v=qp0HIF3SfI4' },
  ],
};

export function sampleLists(lang: Language): Lists {
  const source = SAMPLES[lang] ?? SAMPLES.en;
  return {
    ...emptyLists(),
    goals: toItems(source.goals),
    values: toItems(source.values),
    strengths: toItems(source.strengths),
    gratitude: toItems(source.gratitude),
    affirmations: toItems(source.affirmations),
    quotes: toItems(source.quotes),
  };
}

export function sampleVideos(lang: Language): VideoItem[] {
  const source = SAMPLE_VIDEOS[lang] ?? SAMPLE_VIDEOS.en;
  return source.map((video) => ({ id: newId(), ...video }));
}
